apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: login-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-app-deployment  # Nama deployment yang akan di-scale
  minReplicas: 1  # Jumlah pod minimum
  maxReplicas: 5  # Jumlah pod maksimum
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 # Target penggunaan CPU 80%