apiVersion: v1
kind: Service
metadata:
  name: login-app-service 
spec:
  type: NodePort
  selector:
    app: login-app
  ports:
  - protocol: TCP
    port: 3000       # Port yang diekspos oleh Service di dalam cluster.
    targetPort: 3000 # Port pada Pod tempat traffic akan diteruskan.
