server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Membuat label 'container' dari nama asli kontainer.
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Membuat label 'app' dari label 'app' yang ada di kontainer (jika ada).
      - source_labels: ['__meta_docker_container_label_app']
        target_label: 'app'
      # (Opsional) Tambahkan label 'image' jika ingin filter berdasarkan image
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      # (Opsional) Tambahkan label 'compose_service' jika pakai docker-compose
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'