global:
  scrape_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'login-app'
    static_configs:
      - targets: ['host.docker.internal:30001']
