server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # --- PERBAIKAN: Menambahkan relabel_configs yang lebih pintar ---
    # Aturan ini akan membuat label yang bersih dan mudah digunakan di Grafana.
    relabel_configs:
      # 1. Membuat label 'container' dari nama asli kontainer.
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      # 2. Membuat label 'app' dari label 'app' yang ada di kontainer.
      # Ini adalah kunci utama agar kita bisa mencari log dengan mudah.
      - source_labels: ['__meta_docker_container_label_app']
        target_label: 'app'
